#pragma once

#define DYNAMIC_KEYMAP_LAYER_COUNT 6

#define TAPPING_TERM 200
#define TAPPING_TERM_PER_KEY
#define QUICK_TAP_TERM 150
#define QUICK_TAP_TERM_PER_KEY

#define PERMISSIVE_HOLD

#define COMBO_TERM 30
