name: Build ZMK firmware
on:
  workflow_dispatch:
  push:
    paths-ignore:
      - "keymap-drawer/**"
      - "qmk.json"
      - "keyboards/**"
      - "users/**"
      - "layouts/**"
      - ".github/workflows/qmk-build.yml"

jobs:
  build:
    uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@main
